# Generated by Django 2.0.5 on 2018-06-13 06:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180613_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 6, 7, 43, 732313, tzinfo=utc)),
        ),
    ]
